### ISSUE TITLE
Edits to whole paper

### ISSUE THREAD

**Issue by TGuillerme** [TGuillerme/SpatioTemporal_Disparity#14]
-Included Wilson in intro
-Updated testing section in methods
-Updated results
-Updated discussion

**Comment by TGuillerme** [comment]
Testing if it sends an email.

**Comment by nhcooper123** [comment]
Issues are not commits btw - you should say what needs doing rather than what you've done!

**Comment by TGuillerme** [comment]
Sweet looks like it's working. If you want, you can check the manuscript ([STD_draft.tex](https://github.com/TGuillerme/SpatioTemporal_Disparity/blob/master/Writing/STD_draft.tex)) and check my few changes (namely the new version of the discussion and the results). :crocodile:

**Comment by TGuillerme** [comment]
I've updated the README file for repeatability if you want to have a look at it at some point (no rush though). I will upload the data to figshare sometimes this week :dizzy::ear_of_rice:

**Comment by nhcooper123** [comment]
README looks good, I won't edit it (there are a few typos but nothing serious e.g. development is misspelled) as this is fine and it's your GitHub so should be written in your style! Might be worth mentioning how you'd like people to cite you if they use this - should they cite the paper? Or do you want to get a doi for the repo from zenodo? Up to you.
