### ISSUE TITLE
Referencing style

### ISSUE THREAD

**Issue by nhcooper123** [TGuillerme/SpatioTemporal_Disparity#2]
For ease of editing, can we always use author style referencing in the text, rather than numbers, and then just change at the last minute? Saves me having to read up and down to work out what the refs are in the PDF...

Cheers

Natalie :balloon:

**Comment by TGuillerme** [comment]
Roger that boss, I'll change it straight away in the Missing data paper and will change it as well in the STD one ones you finish editing.
