### ISSUE TITLE
Nature Communication Submission

### ISSUE THREAD

**Issue by TGuillerme** [TGuillerme/SpatioTemporal_Disparity#21]
Hop,

[Here](https://github.com/TGuillerme/SpatioTemporal_Disparity/tree/master/Writing/NatureCom)'s the Nature Communications submission style. You might want to check the:
- [Cover letter](https://github.com/TGuillerme/SpatioTemporal_Disparity/blob/master/Writing/NatureCom/CoverLetter.tex)
- [Shortened title](https://github.com/TGuillerme/SpatioTemporal_Disparity/blob/master/Writing/NatureCom/STD_NatCom.tex) line 104
- [Shortened abstract](https://github.com/TGuillerme/SpatioTemporal_Disparity/blob/master/Writing/NatureCom/STD_NatCom.tex) lines 140-147

Thanks for having a look!
:curly_loop::european_post_office::jack_o_lantern:

**Comment by nhcooper123** [comment]
done!
